//#region NOTE
// fs stuff used in unsorted, test
// included so we won't depend on lib/fs.js import
// that way we can detect lo/deno/nodejs/bun runtime and
// generate types for lo before building it (in some CI)
// runtime abstraction layer for that is still TBD

// typedef stuff
// helper types (to be removed)

// unsorted used in typedef_utils
// typedef_utils related stuff separated into multiple functions

// test
// 1. read globals.d.ts if possible
// 2. collect all block_names from #region <block_name> or #endregion <block_name>
// 3. write out type_segments and nested blocks if needed
// 4. remove block_names that weren't mentioned in type_segments
// 5. write out globals.d.ts (for now just console.log)

// type_segments used in test
// 1. 1st level - segment name
// 2. 2nd level - block name
// 3. can be sync/async function or a string

// typedef_block used in test
// utils to build globals.d.ts string from initial globals.d.ts string

// typedef_utils used in type_segments
// for now find and transform lib/<native_lib_name>/api.js files
//#endregion NOTE

//#region fs stuff
function checkMode(val, mode) {
	return (val & lo.core.S_IFMT) === mode
}

function is_file(path) {
	let MODE_WORD = 6
	if (lo.core.os === 'linux' && lo.core.arch === 'arm64') {
		MODE_WORD = 4
	} else if (lo.core.os === 'mac') {
		MODE_WORD = 1
	}
	const stat = new Uint8Array(160)
	const stat32 = new Uint32Array(stat.buffer)
	const fd = lo.core.open(path, lo.core.O_RDONLY, 0)
	if (fd <= 2) return false
	if (lo.core.fstat(fd, lo.get_address(stat)) !== 0) return false
	lo.core.close(fd)
	return checkMode(stat32[MODE_WORD], lo.core.S_IFREG)
}

function readEntry(handle) {
	const u8 = new Uint8Array(19)
	const dir_view = new DataView(u8.buffer)
	lo.read_memory(lo.get_address(u8), handle, 19)
	const d_ino = dir_view.getUint32(0, true)
	const d_off = dir_view.getUint32(8, true)
	const d_reclen = dir_view.getUint16(16, true)
	const d_type = u8[18]
	const name = lo.utf8_decode(
		handle + 19,
		lo.core.strnlen(handle + 19, lo.core.NAME_MAX),
	)
	return { d_ino, d_off, d_reclen, d_type, name }
}

/** @type {(path: string) => string[]} */
function list_children(path) {
	const { opendir, readdir } = lo.core
	const dir = opendir(path)
	const children = []
	if (!dir) return children
	let next = readdir(dir)
	lo.assert(next)
	while (next) {
		const entry = readEntry(next)
		if (!(entry.name === '..' || entry.name === '.')) {
			children.push(`${path}/${entry.name}`)
		}
		next = readdir(dir)
	}
	lo.assert(lo.core.closedir(dir) === 0)
	return children
}
//#endregion fs stuff

//#region typedef stuff
/**
 * @typedef {{
 *  path: string
 *  module_name: string
 *  local: boolean
 * }} LibApiMeta
 */

/**
 * @typedef {{
 *  lib_name: string
 *  name: string
 *  api: LibApi
 *  constants: LibConstants
 *  mac?: LibPlatform
 *  win?: LibPlatform
 *  linux?: LibPlatform
 *  structs?: string[]
 *  preamble?: string
 *  includes?: string[]
 *  obj?: string[]
 * }} LibApiExports
 */
//#endregion typedef stuff

//#region unsorted
const default_lib_dir_name = 'lib'
const api_file_name = 'api.js'

const get_apis = (lib_dir = default_lib_dir_name) => {
	const filter_js_ts_files = (path = '') => path && !/\.[jt]s/.test(path)
	const modules_set = new Set()
	/**@type {LibApiMeta[]}*/
	const apis = []
	const builtins = lo.builtins()
	const add_api = (local = false, path = '') => {
		const module_name = path.replace(/^.*\/([^\/]+)$/, '$1')
		if (modules_set.has(module_name)) return
		const api_js_path = `${path}/${api_file_name}`
		// check binary
		// check disk
		if (!builtins.includes(api_js_path) && !is_file(api_js_path)) return
		modules_set.add(module_name)
		apis.push({ module_name, path: api_js_path, local })
	}

	list_children(`${lo.getcwd()}/${lib_dir}`)
		.filter(filter_js_ts_files)
		.forEach(add_api.bind(null, true))

	const home = lo.getenv('LO_HOME')
	if (home && home != lib_dir)
		list_children(`${home}/${default_lib_dir_name}`)
			.filter(filter_js_ts_files)
			.forEach(add_api.bind(null, false))

	return apis
}

/**
 * @param {string} path
 * @returns {Promise<LibApiExports>}
 */
export const import_api_js_exports_typed = async (path) => ({
	...await import(path),
	lib_name: path.replace(/.*\/([^\/]+)\/api.js$/, '$1')
})
/**
 * @param {LibApiMeta} x
* @returns {string}
*/
const get_api_js_module_declaration = ({ path, local }) => {
  const declare_module_path = path.replace(local ? lo.getcwd() : lo.getenv('LO_HOME'), '').replace(/^\//, '')
  return `declare module "${declare_module_path}" { export * from '${fake_api_js_module_name}'; }`
}

const get_autogenerated_globals = () => {
  const delimiter = '// ####### !!!DO NOT EDIT CODE BELOW THIS LINE! AUTOGENERATED!!! #######'
  const missing_globals = ['WebAssembly'].join('\n    // ')
  const omit_globals = global_this_base_omit_type().split('=')[1]
    .replace(/[ \n';]+/gm, '').split('|')
  const global_this_base_pick = `"${Object.getOwnPropertyNames(globalThis)
    .filter((s) => !missing_globals.includes(s) && !omit_globals.includes(s))
    .join(`"\n    | "`)}"`
  const autogenerated_str = `${delimiter}
// TODO: add lo.core.engine prop to determine engine
interface CurrentRuntimeGenerics extends RuntimeGenerics<'v8', '${lo.core.os}', '${lo.core.arch}'> {}
// global base type
// keep only things that we have, no need to confuse people
interface GlobalThisBase
  extends Omit<Pick<
    typeof globalThis,
    // list from: lo eval 'console.log(\`"\${Object.getOwnPropertyNames(globalThis).join(\`"    \\n| "\`)}"\`)'
    | ${global_this_base_pick}
    // missing typedefs (extract from typescript DOM lib, we don't need DOM messing with types):
    // WebAssembly issue - https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826
    // ${missing_globals}
  >,
  GlobalThisBaseOmit
  > {}
`
  return autogenerated_str
}

/**@param {LibApiExports[]} lib_exports */
const get_native_libs_string = (lib_exports) => {
  let native_libs_str = ''
  for (let i = 0; i < lib_exports.length; i++) {
    const def = lib_exports[i]
    native_libs_str = `${native_libs_str}  ${def.name}: typeof import('${fake_load_module_name(def.name)}');\n`
  }

  return `interface NativeLibs { ${native_libs_str} }`
}


/**@param {LibApi} api */
const get_lo_lib_api_strings = (api) =>
	Object.keys(api).map((k) => {
		let res = ''
		const api_k = api[k]
		if ('declare_only' in api_k) return res
		const { parameters, result, arch, jsdoc, man, optional } = api_k
		// arch is defined and doesn't match
		if (arch && arch.length && !arch.includes(lo.core.arch)) return res
		const params_strs = parameters.map((v, i) =>
			paramWithType(`p${i}`, optional?.[i], v),
		)
		const jsdoc_str = `${jsdoc ? jsdoc + '\n' : ''}`
		const man_str = `${man ? `// man: ${man}\n` : ''}`
		const ret_str = get_param_type_str(result)
		return `${jsdoc_str}${man_str}  ${k}(${params_strs}): ${ret_str};\n`
	})

/**@param {LibConstants} constants */
const get_lo_lib_constants_strings = (constants) =>
	Object.keys(constants).map(
		(k) => `  ${k}: ${get_param_type_str(constants[k])};\n`,
	)

/**@param {string[]} structs */
const get_lo_lib_structs_strings = (structs) =>
	structs.map((s) => `  struct_${s.split(' ').join('_')}_size: number;\n`)

/**@param {LibApiExports} def */
const get_lo_lib_obj_props_strings = (def) => {
	const platform = def[lo.core.os]
	const structs = [...(def.structs || []), ...(platform?.structs || [])]
	const constants = { ...def.constants, ...platform?.constants }
	const api = { ...def.api, ...platform?.api }
	return [
		...get_lo_lib_api_strings(api),
		...get_lo_lib_constants_strings(constants),
		...get_lo_lib_structs_strings(structs),
	]
}

/**@param {LibApiExports[]} lib_exports */
const get_lo_libs_string = (lib_exports) => {
	let native_libs_str = ''
	for (let i = 0; i < lib_exports.length; i++) {
		const def = lib_exports[i]
		const lib_name = def.lib_name
		const decl_string = def.name
		const decl_props_strings = get_lo_lib_obj_props_strings(def)
		const decl_final_string = `  ${lib_name}: {
  ${decl_string}: {
    ${decl_props_strings.join('    ')}
    }
  }`
		native_libs_str = `${native_libs_str}\n${decl_final_string}`
	}

	return `interface NativeLibs {\n${native_libs_str}\n}`
}

const paramsTypeMap = /**@type {const}*/ ({
	buffer: 'pointer',
	string: 'string',
	u32array: 'Uint32Array',
	bool: 'boolean | 1 | 0',
	void: 'void',
})

/**@typedef {keyof typeof paramsTypeMap} LAPMapped */
/**@typedef {Exclude<LibApiParameter, LAPMapped>} LAPUnmapped */
/**@type {Map<LAPUnmapped, `type ${LAPUnmapped} = number & {${LAPUnmapped}?:never}`>} */
const taggedTypeMap = new Map()
/**@param {LibApiParameter|ConstantType} v */
const get_param_type_str = (v) => {
	if (v in paramsTypeMap) return paramsTypeMap[/**@type {LAPMapped}*/ (v)]
	const vv = /**@type {Exclude<LibApiParameter, LAPMapped>}*/ (v)
	if (typeof v != 'number' && !taggedTypeMap.has(vv))
		// remove ? to error on type cast
		taggedTypeMap.set(vv, `type ${vv} = number & {${vv}?:never}`)
	return vv
}
/**
 * @template {string|number} T
 * @param {T} paramName
 * @param {LibApiParameter} paramType */
const paramWithType = (paramName, opt, paramType) =>
	/**@type {const}*/ (
		`${paramName}${opt ? '?' : ''}: ${get_param_type_str(paramType)}`
	)
//#endregion unsorted

export const test = async () => {
	const {
		replace_block,
		replace_line,
		line_pos,
		find_all_block_names,
		remove_block,
	} = typedef_block
	const globalsdts_name = 'globals.d.ts'
	const cwd = lo.getcwd()
	const home = lo.getenv('LO_HOME')
	const globalsdts_path =
		list_children(`${cwd}`).find((v) => v.includes(globalsdts_name))
		|| list_children(`${home}`).find((v) => v.includes(globalsdts_name))
		// try using cached one
		|| globalsdts_name

	// TODO: optimize
	// instead of holding whole initial string we can detect change in replace_block
	// and also validate that length is equal between start and end
	const initial = is_file(globalsdts_path)
		? new TextDecoder().decode(lo.core.read_file(globalsdts_path))
		: ''
	let res = initial
	const blocks_to_remove = find_all_block_names(res)
	for (const type_segment_name in type_segments) {
		const index = blocks_to_remove.indexOf(type_segment_name)
		if (index !== -1) blocks_to_remove.splice(index, 1)
		const typedef_blocks = type_segments[type_segment_name]
		res = replace_line(res, type_segment_name, true)
		res = replace_line(res, type_segment_name, false)
		for (const typedef_block_name in typedef_blocks) {
			const block_name = `${typedef_block_name}.${type_segment_name}`
			res = await replace_block(
				res,
				block_name,
				typedef_blocks[typedef_block_name],
				line_pos(type_segment_name, false, res),
			)
			const index = blocks_to_remove.indexOf(block_name)
			if (index !== -1) blocks_to_remove.splice(index, 1)
		}
	}

	// TODO: get excludes list from args (or define <config> region in *.d.ts file)
	// we don't have blocks with such names - remove
	for (let i = 0; i < blocks_to_remove.length; i++)
		res = remove_block(res, blocks_to_remove[i])
	// clean gaps
	if (blocks_to_remove.length) res = res.replace(/\n\n+/g, '\n')

	// TODO: remove outside of //#region <block_name>\n<...>//#endregion <block_name> blocks

	// TODO: get out path from args (for now use cwd)
	// if (initial !== res)
	//   lo.core.write_file(`${cwd}/${globalsdts_name}`, new TextEncoder().encode(res))

	console.log(res)
	return res
}
//#endregion test

//#region typedef_block
export const typedef_block = {
	first_line: (name) => `//#region ${name}`,
	last_line: (name) => `//#endregion ${name}`,
	block_regex: (name) => {
		const [start, end] = [
			typedef_block.first_line(name),
			typedef_block.last_line(name),
		]
		return new RegExp(
			start.replace(/([\?\\\/\.])/g, '\\$1')
				+ '[\\s\\S]+'
				+ end.replace(/([\?\\\/\.])/g, '\\$1'),
			'gmi',
		)
	},
	wrap: async (
		name,
		/** @type {string | (() => string)} */ fnOrString,
	) => `${typedef_block.first_line(name)}
${await Promise.resolve(typeof fnOrString === 'string' ? fnOrString : fnOrString())}
${typedef_block.last_line(name)}`,
	replace_block: async (
		/** @type {string} */ source,
		name,
		/** @type {string | (() => string)} */ fnOrString,
		appendBefore = source.length,
	) => {
		const new_typedef_str = await typedef_block.wrap(name, fnOrString)
		// nothing to change
		if (source.includes(new_typedef_str)) return source
		const regex = typedef_block.block_regex(name)
		const has_typedef_block = regex.test(source)
		return has_typedef_block
			? source.replace(regex, new_typedef_str)
			: appendBefore >= source.length
				? `${source}\n${new_typedef_str}`
				: `${source.substring(0, appendBefore)}${new_typedef_str}
${source.substring(appendBefore, source.length)}`
	},
	replace_line: (/** @type {string} */ source, name, is_first = false) => {
		const { first_line, last_line } = typedef_block
		const line = is_first ? first_line(name) : last_line(name)
		const has_line = source.indexOf(line) !== -1
		return has_line ? source : `${source}\n${line}`
	},
	remove_line: (/** @type {string} */ source, name, is_first = false) => {
		const { first_line, last_line } = typedef_block
		const line = is_first ? first_line(name) : last_line(name)
		const has_line = source.indexOf(line) !== -1
		return !has_line
			? source
			: source.replace(`\n${line}`, '').replace(line, '')
	},
	remove_block: (/** @type {string} */ source, name) => {
		const { block_regex, remove_line } = typedef_block
		const regex = block_regex(name)
		if (regex.test(source)) {
			source = source.replace(regex, '')
			if (regex.test(source)) console.log(name)
		} else {
			source = remove_line(source, name, true)
			source = remove_line(source, name, false)
		}
		return source
	},
	line_pos: (name, is_first = false, /** @type {string} */ source) => {
		const { first_line, last_line } = typedef_block
		const line = is_first ? first_line(name) : last_line(name)
		return source.indexOf(line)
	},
	find_all_block_names: (/** @type {string} */ source) => {
		const regex = /^\/\/#(end){0,1}region\s+([^\n]+)\s*$/gim
		/** @type {string[]} */
		const block_names = []
		do {
			const match = regex.exec(source)
			if (!match) break
			const block_name = match[2]
			if (!block_names.includes(block_name)) block_names.push(block_name)
		} while (true)
		return block_names
	},
}
//#endregion typedef_block

//#region typedef_utils
export const typedef_utils = {
	get_apis,
	get_lib_exports: async () =>
		await Promise.all(
			typedef_utils.get_apis()
			.map(({ path }) => import_api_js_exports_typed(path)),
		),
}
//#endregion typedef_utils

//#region type_segments
export const type_segments = /**@type {const}*/ ({
	user_generated: {},
	custom_js_libs: {
		from_dts_files: () =>
			`// TODO: add automatic *.d.ts search in $LO_HOME/lib/** and $PROJECT_DIR/lib/**
// to populate this block (look at typedef_utils.get_apis as reference)`,
	},
	static: {
		base: `/// <reference no-default-lib="true"/>
// NOTE: luckily or unfortunately have to use esnext
/// <reference lib="esnext"/>
// TODO: refine generic NativeLib* types for lib/<module>/api.js (platform)

// generic typedef helper for classes:
// interface IClassX { ... }
// declare var ClassX: Constructor<IClassX>
// TODO: find solution to class declaration issues (TS class declaration !== JS class declaration)
interface Constructor<T> {
  readonly prototype: T;
  new (): T;
}

type OnUnhandledRejection = (error: Error) => void;

type Require = <T extends Record<string | number | symbol, unknown>>(
  file_path: string
) => T | undefined;

interface Console {
  log: (str: unknown) => number;
  error: (str: unknown) => number;
}

// available globally with v8 --expose-gc flag
type GC = undefined | (() => void);

type ENGINE = 'v8';
type OS = 'mac' | 'win' | 'linux';
type ARCH = 'x64' | 'arm64';
type TypedArray =
  | Uint8Array
  | Int8Array
  | Uint16Array
  | Int16Array
  | Uint32Array
  | Int32Array
  | Float32Array
  | Float64Array
  | BigUint64Array
  | BigInt64Array

type Ptr<T extends TypedArray> = T & {
  ptr: pointer;
  size: number;
};

type UnknownLib<T extends string | number> = Record<
  T | string | number | symbol,
  unknown
>;
type Library<T extends string | number> =
  (T extends NativeLibsKeys ? NativeLibXExport<T> : UnknownLib<T>)
    & {
      handle?: number;
      fileName?: string;
      internal?: boolean;
    };

interface RuntimeVersion {
  lo: string;
  v8: string;
}

interface RuntimeGenerics<E extends ENGINE, O extends OS, A extends ARCH> {
  engine: E
  os: O
  arch: A
}

// helpers
type Overwrite<T, U> = Omit<T, keyof U> & U
interface NativeLibs {}
type NativeLibsKeys = keyof NativeLibs;
type NativeLibsExportedKeys = { [k in NativeLibsKeys]: keyof NativeLibs[k] };
type NativeLibX<T extends NativeLibsKeys> = NativeLibs[T][NativeLibsExportedKeys[T]];
type NativeLibXExport<T extends NativeLibsKeys> = Pick<NativeLibs[T], NativeLibsExportedKeys[T]>
`,
		declared_globals: `declare var global: GlobalThis;
declare var onUnhandledRejection: OnUnhandledRejection;
declare var require: Require;
declare var TextEncoder: TextEncoderConstructor;
declare var TextDecoder: TextDecoderConstructor;
declare var lo: Runtime;
declare var gc: GC;
declare var console: Console;`,
		core: `// lo.core = lo.load('core') + overrides listed here
interface Core extends Overwrite<NativeLibX<'core'>, {
  dlsym(handle: number, name: string): number;
  dlopen(path: string, flags: number): number;
  // strnlen(str: string | number, size: number): number;
  /**
   * Reads a file from the given path into a Uint8Array and returns it.
   * @param [path] The path to the file.
   */
  read_file(path: string): Uint8Array;
  /**
   * Creates/Overwrites a file at the specified path with the given Uint8Array
   * as the contents of the file.
   * @param {string}[path] The path of the file to create.
   * @param {TypedArray}[buffer] The data write to the file.
   * @returns {number} Number of bytes written
   */
  write_file(
    path: string,
    buffer: Uint8Array,
    flags?: number,
    mode?: number
  ): number;
  os: OS;
  arch: ARCH;
  engine: ENGINE;
  little_endian: boolean;
  homedir: string;
  defaultWriteFlags: number;
  defaultWriteMode: number;
  mmap(
    ptr: number,
    length: number,
    prot: number,
    flags: number,
    fd: number,
    offset: number,
    buf: Uint32Array
  ): void;
  getcwd(ptr: number, num: number, buf: Uint32Array): void;
  getenv(name: string, buf: Uint32Array): void;
  write_string(num: number, str: string): number;
  readFile(path: string, flags?: number, size?: number): Uint8Array;
  writeFile(
    path: string,
    u8: Uint8Array,
    flags?: number,
    mode?: number
  ): number;

  isFile(path: string): boolean;
  // conditionally defined props
  loader: void | ((specifier: string, resource: string) => string)
  sync_loader: void | ((specifier: string, resource: string) => string)
  binding_loader: void | (<T extends string>(name: T) => Library<T>)
}>{}`,
		lo: `interface Runtime {
  // validate with list from: lo eval 'console.log(\`"\${Object.getOwnPropertyNames(lo).join(\`":unknown;"\`)}":unknown;\`)'
  moduleCache: Map<string, ReturnType<Runtime['loadModule']>>;
  libCache: Map<string, object>;
  requireCache: Map<string, object>;
  start: number;
  errno: number;
  colors: Record<Uppercase<string>, string>;
  core: Core;
  libraries(): string[];
  builtins(): string[];
  assert(expression: any, message?: string | Function): any;
  cstr(str: string): Ptr<Uint8Array>;
  load<T extends NativeLibsKeys>(name: T): NativeLibXExport<T>;
  library<T extends string | number>(name: T): Library<T>;
  /**
   * Prints a string to the console
   * @param [str='a string'] The text to print.
   */
  print(str: string): void;
  exit(status: number): void;
  runMicroTasks(): void;
  hrtime(): number;
  nextTick(callback: Function): void;
  getAddress(buf: TypedArray): number;
  utf8Length(str: string): number;
  utf8EncodeInto(str: string, buf: TypedArray): number;
  utf8EncodeIntoAtOffset(str: string, buf: TypedArray, off: number): number;
  utf8_decode(address: number, len?: number): string;
  latin1Decode(address: number, len?: number): string;
  utf8Encode(str: string): Uint8Array;
  utf8Decode: Runtime['utf8_decode'];
  wrap<
    Handle extends Uint32Array,
    WrappedFnArgs extends unknown[],
    WrappedFnRet,
    State,
  >(
    handle: Handle,
    fn: ((...args: [...WrappedFnArgs]) => WrappedFnRet) & { state?: State },
    plen: number
  ): ((...args: WrappedFnArgs) => number) & { state?: State };
  addr(handle: TypedArray): number;
  version: RuntimeVersion;
  args: string[];
  argv: number;
  argc: number;
  workerSource: string;
  builtin(path: string): string;
  os(): OS;
  arch(): ARCH;
  getenv(str: string): string;
  evaluateModule<T extends object>(identifier: number): Promise<T>;
  loadModule(
    source: string,
    specifier: string
  ): {
    requests: string;
    isSourceTextModule: boolean;
    status: number;
    specifier: string;
    src: string;
    identity: number;
    scriptId: number;
    // js land extensions on returned value
    resource?: string;
    evaluated?: boolean;
    namespace?: object; // module namespace object
  }
  readMemory(dest: pointer, start: number, len: number): void
  wrapMemory(start: number, size: number, free?: number): Uint8Array
  unwrapMemory(buffer: ArrayBuffer): void
  ptr<T extends TypedArray>(u8: T): Ptr<T>
  register_callback(ptr: number, fn: Function): void
  registerCallback: Runtime['register_callback']
  setModuleCallbacks(
    on_module_load: Function,
    on_module_instantiate: Function
  ): void;

  utf8EncodeIntoPtr(str: string, ptr: number): number;
  runScript(source: string, path: string /* resource name */): void;
  pumpMessageLoop(): void;
  readMemoryAtOffset(
    u8: pointer,
    start: number,
    size: number,
    offset: number
  ): void;
  setFlags(str: string): void;
  getMeta: unknown;

  setenv: Core['setenv']
  getcwd(): string
  run_script: Runtime['runScript']
  bindings: Runtime['libraries']
  evaluate_module: Runtime['evaluateModule']
  get_address: Runtime['getAddress']
  get_meta: Runtime['getMeta']
  latin1_decode: Runtime['latin1Decode']
  lib_cache: Runtime['libCache']
  load_module: Runtime['loadModule']
  module_cache: Runtime['moduleCache']
  next_tick: Runtime['nextTick']
  pump_message_loop: Runtime['pumpMessageLoop']
  read_memory: Runtime['readMemory']
  read_memory_at_offset: Runtime['readMemoryAtOffset']
  require_cache: Runtime['requireCache']
  run_microtasks: Runtime['runMicroTasks']
  set_flags: Runtime['setFlags']
  set_module_callbacks: Runtime['setModuleCallbacks']
  unwrap_memory: Runtime['unwrapMemory']
  utf8_encode: Runtime['utf8Encode']
  utf8_encode_into: Runtime['utf8EncodeInto']
  utf8_encode_into_ptr: Runtime['utf8EncodeIntoPtr']
  utf8_encode_into_at_offset: Runtime['utf8EncodeIntoAtOffset']
  utf8_length: Runtime['utf8Length']
  wrap_memory: Runtime['wrapMemory']
}`,
		TextEncoderConstructor: `type TextEncoderConstructor = Constructor<ITextEncoder>;
interface ITextEncoder {
  /**
   * The encoding supported by the \`TextEncoder\` instance. Always set to \`'utf-8'\`.
   */
  readonly encoding: string
  /**
   * UTF-8 encodes the \`input\` string and returns a \`Uint8Array\` containing the
   * encoded bytes.
   * @param [input='an empty string'] The text to encode.
   */
  encode(input?: string): Uint8Array
  /**
   * UTF-8 encodes the \`src\` string to the \`dest\` Uint8Array and returns an object
   * containing the read Unicode code units and written UTF-8 bytes.
   *
   * \`\`\`js
   * const encoder = new TextEncoder()
   * const src = 'this is some data'
   * const dest = new Uint8Array(10)
   * const { read, written } = encoder.encodeInto(src, dest)
   * \`\`\`
   * @param src The text to encode.
   * @param dest The array to hold the encode result.
   */
  encodeInto(src?: string, dest?: Uint8Array): number
}`,
		TextDecoderConstructor: `type TextDecoderConstructor = Constructor<ITextDecoder>;
interface ITextDecoder {
  /**
   * The encoding supported by the \`TextEncoder\` instance. Always set to \`'utf-8'\`.
   */
  readonly encoding: string
  /**
   * UTF-8 decodes the \`Uint8Array\` and returns an \`input\` string.
   */
  decode(ptr_source?: Ptr<Uint8Array> | Uint8Array): string
}`,
		NativeLibApi: `type LIB_API_ARCH = 'x64';
type LIB_API_C_TYPE = 'u64' | 'f64' | 'u32' | 'i64' | 'f32' | 'i32' | 'u8' | 'void' | 'char';
type LIB_API_POINTER = 'pointer'
type LIB_API_BOOL = 'bool';
type LIB_API_STRING = 'string';
type LIB_API_BUFFER = 'buffer';
type LIB_API_TYPED_ARRAY = 'u32array'

type LibApiParameter = LIB_API_POINTER | LIB_API_C_TYPE | LIB_API_STRING
  | LIB_API_BUFFER | LIB_API_TYPED_ARRAY | LIB_API_BOOL;
type LibApiResult = LIB_API_POINTER | LIB_API_C_TYPE | LIB_API_BOOL;
type LibApiPointer = string; // this is sad
type LibApiOverride = { param: number, fastfield: string, slowfield: string } | number;
type LibApiItem = { nofast: boolean; declare_only: boolean; } | {
  parameters: LibApiParameter[]
  optional?: (true | false | 1 | 0 | undefined)[]
  pointers?: (LibApiPointer | void)[]
  result: LibApiResult
  rpointer?: LibApiPointer | [LibApiPointer]
  name?: string
  arch?: ARCH[]
  override?: (LibApiOverride | void)[]
  casts?: (string | void)[]
  jsdoc?: string
  man?: string[] | string
  nofast?: boolean
  nonblocking?: boolean
};
type LibApi = Record<string, LibApiItem>;
type LibApiTypedFn = <const T extends LibApi>(api: T) => T


type ConstantType = Exclude<LIB_API_C_TYPE, 'void' | 'char'> | number;
type LibConstants = Record<string, ConstantType>;
type LibConstsTypedFn = <const T extends LibConstants>(constnats: T) => T

type Platform = 'mac' | 'linux';
interface LibPlatform {
  name: string
  api: LibApi
  constants?: LibConstants
  structs?: string[]
  includes?: string[]
  libs?: string[]
  externs?: string[]
  include_paths?: string[]
  lib_paths?: string[]
  obj?: string[]
  preamble?: string
}
type LibPlatformTypedFn = <const T extends Partial<LibPlatform>>(platform: T) => T
`,
	},
	autogenerated: {
		globals: () => {
			const { declared_globals: declared_global_types } =
				type_segments.static
			const missing_globals = ['WebAssembly'].join('\n    // ')
			const omitted_globals = `type GlobalThisBaseOmit = ${declared_global_types
				.replace(/^.+ var ([A-z]+): ([A-z]+;).*/gm, "--'$1'")
				.split('--')
				.join('  | ')}`
			const omit_globals = omitted_globals
				.split('=')[1]
				.replace(/[ \n';]+/gm, '')
				.split('|')
			const global_this_base_pick = `"${Object.getOwnPropertyNames(
				globalThis,
			)
				.filter(
					(s) =>
						!missing_globals.includes(s)
						&& !omit_globals.includes(s),
				)
				.join(`"\n    | "`)}"`
			return `// TODO: add lo.core.engine prop to determine engine
interface CurrentRuntimeGenerics extends RuntimeGenerics<'v8', '${lo.core.os}', '${lo.core.arch}'> {}
interface GlobalThis extends GlobalThisBase {
${declared_global_types
	.replace(/^.+ var ([A-z]+): ([A-z]+;)/gm, '    $1:$2--')
	.split('--')
	.join('')}
}
    ${omitted_globals}
// global base type
// keep only things that we have, no need to confuse people
interface GlobalThisBase
  extends Omit<Pick<
    typeof globalThis,
    // list from: lo eval 'console.log(\`"\${Object.getOwnPropertyNames(globalThis).join(\`"    \\n| "\`)}"\`)'
    | ${global_this_base_pick}
    // missing typedefs (extract from typescript DOM lib, we don't need DOM messing with types):
    // WebAssembly issue - https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826
    // ${missing_globals}
  >,
  GlobalThisBaseOmit
  > {}`
		},
		native_libs: async () =>
			get_lo_libs_string(await typedef_utils.get_lib_exports()),
		tagged_types_for_native_libs: async () => {
			taggedTypeMap.clear()
			// this stinks
			// we shouldn't generate whole native libs typedef string to populate taggedTypeMap
			await type_segments.autogenerated.native_libs()
			return Array.from(taggedTypeMap.values()).join('\n')
		},
	},
})
//#endregion type_segments
